### PR TITLE
Add vlan aware VMs support (backport nvue)

### PR DESCRIPTION
**Pull request by MoteHue**
Taken from in-progress patch: https://review.opendev.org/c/openstack/networking-generic-switch/+/928490

### CODE REVIEW

**Review by priteau — DISMISSED** [review]
I was concerned about the hardcoded use of `br_default` but this appears to be used elsewhere.

Noting that this is based on an abandoned patch upstream: https://review.opendev.org/c/openstack/networking-generic-switch/+/409133

**Comment by MoteHue** [comment]
> Noting that this is based on an abandoned patch upstream: https://review.opendev.org/c/openstack/networking-generic-switch/+/409133

Was actually based on this patch: https://review.opendev.org/c/openstack/networking-generic-switch/+/928490

**Comment by MoteHue** [comment]
The patch as-is from upstream did not work, as access cannot be set at the same time as vlan/untagged. Added commands to clear one before the other is added

**Comment by priteau** [comment]
> The patch as-is from upstream did not work, as access cannot be set at the same time as vlan/untagged. Added commands to clear one before the other is added

Does the upstream patch need to be updated?

**Review by priteau — APPROVED** [review]

**Comment by MoteHue** [comment]
> > The patch as-is from upstream did not work, as access cannot be set at the same time as vlan/untagged. Added commands to clear one before the other is added
> 
> Does the upstream patch need to be updated?

Yes, I'll follow-up on the patch

**Comment by mnasiadka** [comment]
This patch upstream is not even ready for reviews, and it doesn't fulfil 100% of the functionality, there's no sense to follow up on it.
I'd be happy to understand why do we think we need to send additional commands just to delete the access port configuration, so trunk applies cleanly - while the ports should have no configuration.

**Comment by mnasiadka** [comment]
> > This patch upstream is not even ready for reviews, and it doesn't fulfil 100% of the functionality, there's no sense to follow up on it. I'd be happy to understand why do we think we need to send additional commands just to delete the trunk port configuration, so access port config applies cleanly - while the ports should have no configuration.
> 
> At least on the systems I've been involved with, we've been setting `ngs_port_default_vlan` so that nodes return to `access prov_wl`.

Now with the additional context - it makes sense, I've never used ngs_port_default_vlan ;-)

**Pull request merged**
