### PR TITLE
Apply Xena backports from Wallaby

### PR DESCRIPTION
**Pull request by markgoddard**

### CODE REVIEW

**Review by priteau — APPROVED** [review]

**Comment by priteau** [comment]
I ran unit tests manually, which passed. We should add a workflow for them.

**Comment by markgoddard** [comment]
> I ran unit tests manually, which passed. We should add a workflow for them.

Release train should handle this. Unsure why it hasn't. @jackhodgkiss ?

**Comment by markgoddard** [comment]
> > I ran unit tests manually, which passed. We should add a workflow for them.
> 
> Release train should handle this. Unsure why it hasn't. @jackhodgkiss ?

Looks like the workflows are present. Perhaps this branch did not include them

**Comment by priteau** [comment]
> > > I ran unit tests manually, which passed. We should add a workflow for them.
> > 
> > 
> > Release train should handle this. Unsure why it hasn't. @jackhodgkiss ?
> 
> Looks like the workflows are present. Perhaps this branch did not include them

Right, there was no `.github` directory on this branch.

**Pull request merged**
